### ISSUE TITLE
ReactiveNestedCalibrator dos not work well

### ISSUE THREAD

**Issue by Lowerce** [JohannesBuchner/UltraNest#145]
* UltraNest version: 4.3.2
* Python version: 3.9
* Operating System: macOS 14.6.1

### Description

I follow the command recommended in [ReactiveNestedCalibrator](https://johannesbuchner.github.io/UltraNest/ultranest.html#ultranest.calibrator.ReactiveNestedCalibrator). But it seems nothing output.

### What I Did

```
sampler = ReactiveNestedCalibrator(my_param_names, my_loglike, my_transform) 
sampler.stepsampler = SliceSampler(nsteps=10, generate_direction=region_oriented_direction)
sampler.run(min_num_livepoints=400)
```

**Comment by JohannesBuchner** [comment]
That is very strange! Is this in a python script or a notebook? Can you rerun it from scratch?

**Comment by Lowerce** [comment]
> That is very strange! Is this in a python script or a notebook? Can you rerun it from scratch?

In a python script. The corresponding one could work well:
```
sampler = ReactiveNestedSampler(my_param_names, my_loglike, my_transform)
sampler.stepsampler = SliceSampler(nsteps=10, generate_direction=region_oriented_direction)
sampler.run(min_num_livepoints=400)
```
How could I "return it from scratch"? I would like to try.
**ReactiveNestedCalibrator** seems behavior different with **ReactiveNestedSampler** for I can't get the return value of *sampler.run* from **ReactiveNestedCalibrator**. It will return an *<generator object ReactiveNestedCalibrator.run at 0x1467de3c0>*.

By the way, the *plot* method implemented in **ReactiveNestedCalibrator** could not work well too. The following issue is raised:
```
self.sampler.stepsampler.plot(os.path.join(self.sampler.logs['plots'], 'stepsampler.pdf'))
AttributeError: 'ReactiveNestedCalibrator' object has no attribute 'sampler'
```

**Comment by JohannesBuchner** [comment]
I'm quite confused. if you call run() then you should at least get to the first print here: https://github.com/JohannesBuchner/UltraNest/blob/master/ultranest/calibrator.py#L97

**Comment by shiningsurya** [comment]
sorry for interjecting here, this is something i also faced. 

`ReactiveNestedCalibrator` returns generator of list of `[nstep, result]`. 
Only when you access, the actual sampling is performed. 

i am running it like 
```python
for nstep, results in sampler:
    print(f" {nstep:d}", results, sep='\n')
```

**Comment by JohannesBuchner** [comment]
Please propose a fix -- maybe run_iter (which gives the iterator) and run (which returns the list), like ReactiveNestedSampler.

**Comment by lwelzel** [comment]
I am encountering the same issue. With:

```python
sampler = ultranest.calibrator.ReactiveNestedCalibrator(my_param_names, my_loglike, my_transform)
sampler.stepsampler = ultranest.stepsampler.SliceSampler(nsteps=10, generate_direction=region_oriented_direction)
results = sampler.run(min_num_livepoints=400)
```
Nothing actually runs (not even the first print statement) I when I try to print or plot the output it fails similar to what @Lowerce posted.

However, I noticed that in the error message the sampler flags not having a `.sampler` attribute which made me pause. Setting:

```python
sampler = ultranest.calibrator.ReactiveNestedCalibrator(my_param_names, my_loglike, my_transform)
sampler.sampler = ultranest.ReactiveNestedSampler(my_param_names, my_loglike, my_transform) # note that I add the sampler to the calibrator namespace
sampler.sampler.stepsampler = ultranest.stepsampler.SliceSampler(nsteps=10, generate_direction=region_oriented_direction)
results = sampler.run(min_num_livepoints=400)

print(results)
sampler.plot()
```
I get a bit more:
```
Creating directory for new run /home/.../run
<generator object ReactiveNestedCalibrator.run at 0x7fec219ab640>
jump distance diagnostic:
Traceback (most recent call last):
  File "/ultranest_runner.py", line 2515, in <module>
    out = runner.run(cfg, backend, init_center_all=None, progress=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ultranest_runner.py", line 2445, in run
    self.sampler.plot()
  File "/home/lwelzel/.conda/envs/ppdnet/lib/python3.12/site-packages/ultranest/calibrator.py", line 199, in plot
    for nsteps, relsteps, result in zip(self.nsteps, self.relsteps, self.results):
                                        ^^^^^^^^^^^
AttributeError: 'ReactiveNestedCalibrator' object has no attribute 'nsteps'

```

This seems like there is potentially a problem with the namespace? However (again), nothing is run when starting the calibration with `sampler.run(...)`. Any help is greatly appreciated!

---
If I try to run/print the output like @shiningsurya suggested, the sampling starts but I am unsure if the calibrator is working since correctly then.

**Comment by JohannesBuchner** [comment]
plot() does not work because run() did not do anything yet. You need to wrap run as discussed above.

I would suggest that we modify run() here https://github.com/JohannesBuchner/UltraNest/blob/master/ultranest/calibrator.py#L98 and rename it to run_iter(), and add a new method run() that essentially contains:

```python
for nsteps, results in self.run_iter(*args, **kwargs):
    print(f" {nsteps:d}", results)
return results
```
