### ISSUE TITLE
Issue / bug with initialization of information variable (H) in SingleCounter and MultiCounter classes?

### ISSUE THREAD

**Issue by abhimat** [JohannesBuchner/UltraNest#157]
I noticed the following error when using the `resume_from_similar_file()` function in ultranest:

```
Traceback (most recent call last):
  File "/u/home/a/abhimat/research/2023_S2-36_analysis/phitter_fits/202411_3/fit_un_2_Kbb_HeII_only_RVs/run_un_fit.py", line 391, in <module>
    sampler = ultranest.ReactiveNestedSampler(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u/home/a/abhimat/.conda/envs/phoebe_py38/lib/python3.12/site-packages/ultranest/integrator.py", line 1219, in __init__
    resume_from_similar_file(
  File "/u/home/a/abhimat/.conda/envs/phoebe_py38/lib/python3.12/site-packages/ultranest/integrator.py", line 342, in resume_from_similar_file
    main_iterator2.passing_node(node2, active_nodes2)
  File "/u/home/a/abhimat/.conda/envs/phoebe_py38/lib/python3.12/site-packages/ultranest/netiter.py", line 536, in passing_node
    self.H = exp(wi - logZnew) * Li + exp(self.logZ - logZnew) * (self.H + self.logZ) - logZnew
                                                                  ~~~~~~~^~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
```

Upon investigating this issue, It appears to stem from this particular line
https://github.com/JohannesBuchner/UltraNest/blob/fbde672781762ef01aa24b46bdd01c614e0b0005/ultranest/netiter.py#L536

and how the information variable (`self.H`) appears to be getting initialized in both the SingleCounter and MultiCounter classes, as `None` in SingleCounter and an array of NaNs in MultiCounter:
https://github.com/JohannesBuchner/UltraNest/blob/fbde672781762ef01aa24b46bdd01c614e0b0005/ultranest/netiter.py#L483-L492
https://github.com/JohannesBuchner/UltraNest/blob/fbde672781762ef01aa24b46bdd01c614e0b0005/ultranest/netiter.py#L630-L655

Am I correct in initializing `self.H = 0`? Upon trying it for my use case, it appears to fix the issue.

Just wanted to double check about the initial value before submitting a pull request with the fix, thank you!

**Comment by JohannesBuchner** [comment]
Sorry, I missed this issue somehow. Your solution seems reasonable, please open a PR, ideally with a unit test that fails without the change.
