### ISSUE TITLE
Unable to restart job. HDF5 error, possibly broken points.h5 file. 

### ISSUE THREAD

**Issue by ajdittmann** [JohannesBuchner/UltraNest#21]
* UltraNest version: 3.2.0 (installed through pip)
* Python version: 3.8.5 (Anaconda) 
* Operating System: RHEL 8

### Description
I've been able to get large runs going with MPI on my local cluster, which uses SLURM for job submission. It has worked well for smaller tasks. For larger jobs, things seemed to be going fine, I'd been able to start jobs, and this particular job was able to restart multiple times without issue after the previous submission timed out. However, on the 5th restart the job fails with the following error message: 

```
Traceback (most recent call last):
  File "/homes/dittmann/python/anaconda3/lib/python3.8/site-packages/h5py/_hl/files.py", line 185, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (wrong B-tree signature)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "syntheticTest.py", line 24, in <module>
    sampler = ReactiveNestedSampler(paramnames, loglike, transform=transform,
  File "/homes/dittmann/python/anaconda3/lib/python3.8/site-packages/ultranest/integrator.py", line 1049, in __init__
    self.pointstore = HDF5PointStore(storage_filename, storage_num_cols, mode='a' if resume else 'w')
  File "/homes/dittmann/python/anaconda3/lib/python3.8/site-packages/ultranest/store.py", line 186, in __init__
    self.fileobj = h5py.File(filepath, **h5_file_args)
  File "/homes/dittmann/python/anaconda3/lib/python3.8/site-packages/h5py/_hl/files.py", line 406, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/homes/dittmann/python/anaconda3/lib/python3.8/site-packages/h5py/_hl/files.py", line 187, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 108, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = 'logs/synthetic400HzRNS-8d/results/points.hdf5', errno = 17, error message = 'File exists', flags = 15, o_flags = c2)

```

When I try to use h5ls to check out the results/points.h5 file, I get the following:
```
H5tools-DIAG: Error detected in HDF5:tools (1.10.6) thread 0:
  #000: h5trav.c line 1064 in h5trav_visit(): traverse failed
    major: Failure in tools library
    minor: error in function
  #001: h5trav.c line 297 in traverse(): H5Literate_by_name failed
    major: Failure in tools library
    minor: error in function
```
My guess is that the job may have just timed out while files were being written so they are incomplete. Do have any ideas on how to test this? Or could there be some other problem? The final output of the slurm file the last time the job successfully started doesn't have anything out of the ordinary, nor does the debug.log file. Let me know if attaching any other files could help get to the bottom of this.

**Comment by JohannesBuchner** [comment]
Perhaps the hdf5 is still open by another program, or multiple processes tried to create it at the same time?

**Comment by ajdittmann** [comment]
Sorry for the delayed reply. The hdf5 file was definitely corrupted. I could not determine if it was caused by multiple processes trying to create it at the same time or because the job timed out mid-write. 
If it would not be too much trouble or overhead, writing a backup hdf5 file every N updates, possibly optionally, might be a worthwhile feature.
