### ISSUE TITLE
AssertionError: Error in loglikelihood function: returned non-finite number:

### ISSUE THREAD

**Issue by sameeresque** [JohannesBuchner/UltraNest#5]
* UltraNest version:2.1.0
* Python version:Python 2.7.14 |Anaconda, Inc.| (default, Oct 16 2017, 17:29:19) 
[GCC 7.2.0] on linux2
* Operating System:Red Hat Enterprise Linux Server release 6.10 (Santiago)

AssertionError: Error in loglikelihood function: returned non-finite number:

Using the same likelihood function that yielded expected results on MultiNest, I ran it using UltraNest. I'm getting the assertion error that a non-finite number is returned.

### What I Did
I modified the likelihood to account for NaN
```
    if math.isnan(lnprobval):
        return -np.inf
    else:
        return lnprobval

```
Here's the traceback without modification:
```
Traceback (most recent call last):
  File "testing_ultranest.py", line 516, in <module>
    resume=True, # whether to resume from there (otherwise start from scratch)
  File "/storage/home/sxx15/.conda/envs/envsam/lib/python2.7/site-packages/ultranest/integrator.py", line 723, in __init__
    self._set_likelihood_function(transform, loglike, num_test_samples)
  File "/storage/home/sxx15/.conda/envs/envsam/lib/python2.7/site-packages/ultranest/integrator.py", line 765, in _set_likelihood_function
    assert np.isfinite(logl).all(), ("Error in loglikelihood function: returned non-finite number: %s for input u=%s p=%s" % (logl, u, p))
AssertionError: Error in loglikelihood function: returned non-finite number: [nan nan] for input u=[[0.15287676 0.02828641 0.38913538 0.94604033 0.01679531 0.16236183
  0.99140184 0.18091045]
 [0.13509187 0.91037108 0.40966697 0.84476043 0.21779403 0.16916286
  0.13342418 0.99614286]] p=[[-2.38849296 -4.91514076 -1.44345849 -2.161879   -2.93281876 -3.67527633
   0.96560737 -3.6381791 ]
 [-2.45963253 -2.26888676 -1.36133212 -2.46571871 -2.12882389 -3.66167427
  -2.46630329 -2.00771427]]

```
With modification:
Traceback (most recent call last):
```
  File "testing_ultranest.py", line 519, in <module>
    resume=True, # whether to resume from there (otherwise start from scratch)
  File "/storage/home/sxx15/.conda/envs/envsam/lib/python2.7/site-packages/ultranest/integrator.py", line 723, in __init__
    self._set_likelihood_function(transform, loglike, num_test_samples)
  File "/storage/home/sxx15/.conda/envs/envsam/lib/python2.7/site-packages/ultranest/integrator.py", line 765, in _set_likelihood_function
    assert np.isfinite(logl).all(), ("Error in loglikelihood function: returned non-finite number: %s for input u=%s p=%s" % (logl, u, p))
AssertionError: Error in loglikelihood function: returned non-finite number: [-inf -inf] for input u=[[0.748844   0.1997127  0.36582737 0.61027022 0.04760576 0.99153052
  0.20760386 0.95238083]
 [0.88866919 0.19656596 0.11957994 0.27902825 0.18068189 0.71918241
  0.28413969 0.81962967]] p=[[-0.004624   -4.40086191 -1.53669051 -3.16918935 -2.80957697 -2.01693897
  -2.16958456 -2.09523834]
 [ 0.55467678 -4.41030212 -2.52168023 -4.16291525 -2.27727244 -2.56163519
  -1.86344124 -2.36074067]]


```

**Comment by JohannesBuchner** [comment]
Yeah, infinite values are not good return values... if you need a small value, try -1e300 or sys.float_info.min .

**Comment by sameeresque** [comment]
Thank you!

**Comment by astronasko** [comment]
> Yeah, infinite values are not good return values... if you need a small value, try -1e300 or sys.float_info.min .

Hi Dr Buchner, just chiming in, in case you meant `-sys.float_info.max` here. I also wondered, would the choice of constant influence the final model logZ? @JohannesBuchner

**Comment by JohannesBuchner** [comment]
It should not matter. 

It is best to avoid large prior volumes that have such constants, see https://github.com/JohannesBuchner/UltraNest/issues/81#issuecomment-1571513539 for slight refinements.
